services:

  mlflow:
    image: python:3.14-slim
    working_dir: /app
    volumes:
      - ./mlflow.db:/app/mlflow.db
      - ./mlartifacts:/app/mlartifacts
    command: >
      sh -c "
      pip install --no-cache-dir mlflow==3.16.1 &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///app/mlflow.db
      --default-artifact-root /app/mlartifacts
      --allowed-hosts 'localhost,127.0.0.1,mlflow,mlflow:5000,host.docker.internal:5000'
      "
    ports:
      - "5000:5000"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mlflow
    ports:
      - "8000:8000"
    environment:
      MODEL_URI: /model
      MODEL_THRESHOLD: "0.07"
    volumes:
      - ./mlartifacts/models/m-c1231275316d4aeaa38656359914e4d5/artifacts:/model:ro